extends Node

signal card_played(card: Card, player: Player, targets: Array)
signal card_drawn(card: Card, player: Player)
signal card_discarded(card: Card, player: Player)
signal damage_dealt(source: Player, target: Player, amount: int, damage_type: GameEnums.CardSubType)
signal damage_prevented(target: Player, amount: int, reason: String)
signal healing_applied(source: Player, target: Player, amount: int)
signal hero_died(player: Player, killer: Player)
signal hero_revived(player: Player)
signal turn_started(player: Player)
signal turn_ended(player: Player)
signal phase_changed(player: Player, old_phase: GameEnums.TurnPhase, new_phase: GameEnums.TurnPhase)
signal identity_revealed(player: Player, identity: GameEnums.Identity)
signal equipment_equipped(player: Player, card: Card, slot: GameEnums.EquipmentSlot)
signal equipment_unequipped(player: Player, card: Card, slot: GameEnums.EquipmentSlot)
signal judge_result(player: Player, card: Card, success: bool)
signal skill_triggered(player: Player, skill_name: String)
signal skill_resolved(player: Player, skill_name: String)
signal game_started(players: Array)
signal game_over(winner_identity: GameEnums.Identity)
signal request_response(player: Player, card_sub_type: GameEnums.CardSubType, source_card: Card)
signal response_provided(player: Player, card: Card)
signal animation_finished(animation_name: String)
signal turn_phase_action_required(player: Player, phase: GameEnums.TurnPhase)
signal turn_phase_action_completed(player: Player, phase: GameEnums.TurnPhase)
